// This file was automatically generated by the revision extractor.
// There is no need to modify this file.

#ifndef GIT_VERSION_HPP
#define GIT_VERSION_HPP

#define BUILD_TAG "4.0-TRUNK"
#define BUILD_HASH 0xe13fd4b
#define COMMIT_TIMESTAMP 1321621262
#define BUILD_HASH_STR "e13fd4b"
#define BUILD_USER_STR "chaotic"
#define BUILD_HOST_STR "Chaotic"

static int BUILD_REVISION = 0;

#endif


