// This file was automatically generated by the revision extractor.
// There is no need to modify this file.

#ifndef SVN_REVISION_H
#define SVN_REVISION_H

static const char* BUILD_TAG = "4.0-TRUNK";
static int BUILD_REVISION = 4424;


#endif
